CREATE TABLE menu_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  goods_type VARCHAR(50) NOT NULL,
  item_name VARCHAR(50) NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
